"""
mongol-shape-data — flat shaping rules for Traditional Mongolian script.

The rules JSON files in `rules/` are language-agnostic. They are generated by
`scripts/preprocess.py` from the mongfontbuilder package + UTN #57 data, but
the output has no Python-specific structure: any language with a JSON parser
can consume them.

Python users should call `load_rules(locale)` to get a parsed dict.
"""
import json
from importlib.resources import files
from typing import Any, Dict

__version__ = "0.1.0"

SCHEMA_VERSION = 1

SUPPORTED_LOCALES = ("MNG", "MNGx", "TOD", "TODx", "SIB", "MCH", "MCHx")


def load_rules(locale: str) -> Dict[str, Any]:
    """
    Load the flat shaping-rules JSON for a given locale.

    Raises FileNotFoundError if the locale has no generated rules file yet.
    """
    base = locale.removesuffix("x") if locale.endswith("x") else locale
    path = files(__package__) / "rules" / f"{base}.json"
    with path.open(encoding="utf-8") as f:
        return json.load(f)


def rules_path(locale: str):
    """Return the filesystem path to the rules JSON for `locale`."""
    base = locale.removesuffix("x") if locale.endswith("x") else locale
    return files(__package__) / "rules" / f"{base}.json"
