#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Generate the static Rust data tables for the Rust core (the crate at the repository root).

Reads the language-agnostic JSON in `python/mongol_norm/data/` -- the same files the
Python tooling (`mongol_norm._data`) loads -- and emits `src/generated/*.rs`:

  enums.rs            WrittenUnit / Condition / Alias enums (union over all locales)
  mng.rs tod.rs ...   per-locale shaping tables (letters, variants, categories, particles)
  mng_normalize.rs    the MNG normalize-encoder tables
  mod.rs              module declarations

The output is deterministic (no timestamps, stable ordering), so `--check`
regenerates into memory and fails when any committed file differs.
python/tests/test_rust_twin.py runs that check in the Python test suite.

    python3 python/scripts/gen_rust_tables.py          # (re)generate
    python3 python/scripts/gen_rust_tables.py --check  # verify freshness; exit 1 if stale

Python 3.9+, standard library only.
"""
import argparse
import hashlib
import json
import re
import sys
from pathlib import Path

# The repository root is the crate root: python/scripts/<this file> -> two levels up.
ROOT = Path(__file__).resolve().parents[2]
DATA = ROOT / "python" / "mongol_norm" / "data"
OUT = ROOT / "src" / "generated"

LOCALES = ("MNG", "TOD", "SIB", "MCH")
NORMALIZE_LOCALES = ("MNG",)
STRUCTURAL_UNITS = ("Mvs", "Nirugu", "Zwj")
POSITIONS = ("isol", "init", "medi", "fina")
SCHEMA_VERSION = 1
NORMALIZE_SCHEMA = "mongol-normalize-table/2"
CANONICAL_VERSION = "mng-canonical/3"
MAX_UNIT_KEY_LEN = 3  # src/normalize.rs::UnitKey capacity
# The encoder context's key components, in packing order, with their bit widths. Must equal
# src/encoder.rs (COMPONENT_BITS) and examples/gen_normalize_table/context.rs (COMPONENTS).
CONTEXT_COMPONENTS = (
    ("prev_letter", 6), ("prev_fvs", 3), ("prev_position", 3), ("prev_written", 8),
    ("prev_token", 3), ("mvs_since_prev", 1), ("cluster", 1), ("masculine", 1),
    ("particle", 10), ("promise", 3),
)
PROMISES = ("vowel", "vowel_not_ee", "masculine", "feminine_or_neutral", "consonant_or_ee")
# Must equal the code points hard-coded in src/unicode.rs (MVS, NIRUGU, ZWJ) and
# src/tables.rs (Fvs::cp).
CONSTANTS = {
    "MVS": "180E", "NIRUGU": "180A", "ZWJ": "200D",
    "FVS1": "180B", "FVS2": "180C", "FVS3": "180D", "FVS4": "180F",
}
FVS_CP_TO_INDEX = {"180B": 1, "180C": 2, "180D": 3, "180F": 4}

UNIT_NAME = re.compile(r"^[A-Z][A-Za-z0-9]*$")
CONDITION_NAME = re.compile(r"^[a-z][a-z0-9_]*$")
ALIAS_NAME = re.compile(r"^[a-z][a-z0-9]*$")

HEADER = "// @generated by python/scripts/gen_rust_tables.py -- DO NOT EDIT.\n"


def die(message):
    raise SystemExit("gen_rust_tables: " + message)


def digest(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()[:16]


def condition_variant(name):
    if not CONDITION_NAME.match(name):
        die("bad condition name {!r}".format(name))
    return "".join(part.capitalize() for part in name.split("_"))


def alias_variant(alias):
    if not ALIAS_NAME.match(alias):
        die("bad alias {!r}".format(alias))
    return alias[0].upper() + alias[1:]


def unit_variant(unit):
    if not UNIT_NAME.match(unit):
        die("bad written unit name {!r}".format(unit))
    return unit


def position_variant(position):
    if position not in POSITIONS:
        die("bad position {!r}".format(position))
    return "Position::" + position.capitalize()


def fvs_expr(index):
    if index == 0:
        return "None"
    if index not in (1, 2, 3, 4):
        die("bad fvs {!r}".format(index))
    return "Some(Fvs::Fvs{})".format(index)


def hex_cp(value):
    return "0x{:04X}".format(value)


# ── loading + validation ───────────────────────────────────────────────

def load_rules():
    rules = {}
    aliases = {}
    for locale in LOCALES:
        path = DATA / (locale + ".json")
        with path.open(encoding="utf-8") as stream:
            doc = json.load(stream)
        if doc.get("schema_version") != SCHEMA_VERSION:
            die("{}: schema_version {!r} != {}".format(path.name, doc.get("schema_version"), SCHEMA_VERSION))
        if doc.get("locale") != locale:
            die("{}: locale is {!r}, expected {!r}".format(path.name, doc.get("locale"), locale))
        aliases[locale] = validate_rules(locale, doc)
        rules[locale] = doc
    return rules, aliases


def validate_rules(locale, doc):
    seen_keys = set()
    defaults = set()
    slots = set()
    aliases = {}
    for letter in doc["letters"]:
        alias = letter.get("alias")
        if not alias:
            die("{}: letter U+{:04X} has no alias".format(locale, letter["cp"]))
        alias_variant(alias)
        if alias in aliases:
            die("{}: duplicate alias {!r}".format(locale, alias))
        aliases[alias] = letter["cp"]
        if not letter["variants"]:
            die("{}: letter {!r} has no variants".format(locale, alias))
        for variant in letter["variants"]:
            position_variant(variant["position"])
            fvs_expr(variant["fvs"])
            key = (letter["cp"], variant["position"], variant["fvs"])
            if key in seen_keys:
                die("{}: duplicate variant {!r}".format(locale, key))
            seen_keys.add(key)
            slots.add((letter["cp"], variant["position"]))
            written = variant["written"]
            if not written or len(written) > MAX_UNIT_KEY_LEN:
                die("{}: variant {!r} has {} written units".format(locale, key, len(written)))
            for unit in written:
                unit_variant(unit)
                if unit in STRUCTURAL_UNITS:
                    die("{}: written unit {!r} collides with a structural token".format(locale, unit))
            for condition in variant["conditions"]:
                condition_variant(condition)
            if variant["default"]:
                if (letter["cp"], variant["position"]) in defaults:
                    die("{}: two defaults for {!r}".format(locale, key[:2]))
                defaults.add((letter["cp"], variant["position"]))
    missing = slots - defaults
    if missing:
        die("{}: (cp, position) without a default variant: {!r}".format(locale, sorted(missing)))
    for category, members in doc["categories"].items():
        for alias in members:
            if alias not in aliases:
                die("{}: category {!r} names unknown alias {!r}".format(locale, category, alias))
    for key, indices in doc["particles"].items():
        parts = key.split(" ")
        for part in parts:
            if part != "mvs" and part not in aliases:
                die("{}: particle {!r} names unknown alias {!r}".format(locale, key, part))
        for index in indices:
            if not isinstance(index, int) or not 0 <= index < len(parts):
                die("{}: particle {!r} has bad index {!r}".format(locale, key, index))
    return aliases


def load_normalize(rules, aliases):
    tables = {}
    for locale in NORMALIZE_LOCALES:
        path = DATA / (locale + ".normalize.json")
        with path.open(encoding="utf-8") as stream:
            doc = json.load(stream)
        if doc.get("schema") != NORMALIZE_SCHEMA:
            die("{}: schema {!r}".format(path.name, doc.get("schema")))
        if doc.get("canonical_version") != CANONICAL_VERSION:
            die("{}: canonical_version {!r}".format(path.name, doc.get("canonical_version")))
        if doc.get("locale") != locale:
            die("{}: locale is {!r}, expected {!r}".format(path.name, doc.get("locale"), locale))
        for name, value in CONSTANTS.items():
            if doc["constants"].get(name) != value:
                die("{}: constant {} is {!r}, expected {!r}".format(path.name, name, doc["constants"].get(name), value))
        validate_normalize(locale, doc, rules, aliases[locale])
        tables[locale] = doc
    return tables


def locale_units(doc):
    return {unit for letter in doc["letters"] for variant in letter["variants"] for unit in variant["written"]}


def enum_units(rules):
    """The WrittenUnit enum order (render_enums): every unit of every locale plus the tokens."""
    units = set(STRUCTURAL_UNITS)
    for doc in rules.values():
        units.update(locale_units(doc))
    return sorted(units)


def projection_bits(names, where):
    known = [name for name, _bits in CONTEXT_COMPONENTS]
    bits = 0
    for name in names:
        if name not in known:
            die("{}: unknown context component {!r}".format(where, name))
        bits |= 1 << known.index(name)
    return bits


def validate_table(where, table, check_value):
    projection_bits(table["projection"], where)
    check_value(table["default"])
    keys = []
    for key, value in table["rows"]:
        keys.append(int(key, 16))
        check_value(value)
    if keys != sorted(set(keys)):
        die("{}: rows are not sorted by key".format(where))


def validate_normalize(locale, doc, rules, aliases):
    rules_doc = rules[locale]
    units = locale_units(rules_doc)
    cps = {letter["cp"] for letter in rules_doc["letters"]}
    if [tuple(c) for c in doc["context_components"]] != list(CONTEXT_COMPONENTS):
        die("{}: context_components differ from the encoder's".format(locale))
    if [name for name, _letters in doc["promises"]] != list(PROMISES):
        die("{}: promises differ from the encoder's".format(locale))
    for name, letters in doc["promises"]:
        for alias in letters:
            if alias not in aliases:
                die("{}: promise {!r} names unknown alias {!r}".format(locale, name, alias))
    if doc["mask_units"] != enum_units(rules):
        die("{}: mask_units is not the WrittenUnit order".format(locale))
    for set_ in doc["mask_sets"]:
        if len(set_) != 6:
            die("{}: a mask set needs six masks".format(locale))
        for mask in set_:
            if int(mask, 16) >> len(doc["mask_units"]):
                die("{}: mask {} has bits beyond the unit list".format(locale, mask))
    written = doc["written_sequences"]
    if written != sorted(set(written)):
        die("{}: written_sequences must be sorted and unique".format(locale))
    nodes = doc["particle_nodes"]
    if nodes[:2] != ["", "M:"] or len(set(nodes)) != len(nodes) or len(nodes) >= 1023:
        die("{}: bad particle_nodes roots / size".format(locale))
    for name in nodes[2:]:
        parent, alias = particle_parent(name)
        if parent not in nodes or alias not in aliases:
            die("{}: particle node {!r} has no parent or an unknown alias".format(locale, name))
    by_slot = {}
    for index, cand in enumerate(doc["candidates"]):
        where = "{}: candidate {}".format(locale, index)
        if aliases.get(cand["letter"]) != int(cand["cp"], 16) or int(cand["cp"], 16) not in cps:
            die("{} has letter {!r} / cp {!r}".format(where, cand["letter"], cand["cp"]))
        if cand["fvs"] is not None and cand["fvs"] not in FVS_CP_TO_INDEX:
            die("{} has bad fvs {!r}".format(where, cand["fvs"]))
        position_variant(cand["position"])
        for field in ("units", "written"):
            parts = cand[field].split("+")
            if len(parts) > MAX_UNIT_KEY_LEN or any(unit not in units for unit in parts):
                die("{} has bad {} {!r}".format(where, field, cand[field]))
        if cand["written"] not in written:
            die("{}: written {!r} missing from written_sequences".format(where, cand["written"]))
        robust = cand["robust"]
        if isinstance(robust, dict):
            def mask_set(value, where=where):
                if not isinstance(value, int) or not 0 <= value < len(doc["mask_sets"]):
                    die("{}: bad mask-set index {!r}".format(where, value))
            validate_table(where, robust, mask_set)
        elif robust not in ("always", "never"):
            die("{}: bad robust {!r}".format(where, robust))
        by_slot.setdefault((cand["position"], cand["units"]), []).append(index)
    for entry in doc["finals"]:
        where = "{}: final {}/{}".format(locale, entry["position"], entry["units"])
        if entry["position"] not in ("isol", "fina"):
            die("{}: final letters are isol or fina".format(where))
        group = by_slot.get((entry["position"], entry["units"]), [])

        def valid(value, where=where, group=group):
            if not isinstance(value, str) or int(value, 16) >> len(group):
                die("{}: validity mask {!r} names options the group does not have".format(where, value))
        if isinstance(entry["valid"], dict):
            validate_table(where, entry["valid"], valid)
        else:
            valid(entry["valid"])
    for unit in doc["known_units"]:
        if unit not in units:
            die("{}: known_units names unknown unit {!r}".format(locale, unit))
    for record in doc["positioned_units"]:
        if record["unit"] not in units:
            die("{}: positioned_units names unknown unit {!r}".format(locale, record["unit"]))
        position_variant(record["position"])


def particle_parent(name):
    """`M:a ch a` -> (`M:a ch`, `a`); `u` -> (``, `u`)."""
    root = "M:" if name.startswith("M:") else ""
    body = name[len(root):]
    if " " in body:
        head, alias = body.rsplit(" ", 1)
        return root + head, alias
    return root, body


# ── rendering ──────────────────────────────────────────────────────────

def provenance(paths):
    lines = []
    for path in paths:
        lines.append("// Source: {} (sha256 {})\n".format(path.relative_to(ROOT).as_posix(), digest(path)))
    return "".join(lines)


def render_enum(name, doc, entries, kind, extra_methods=""):
    """entries: list of (variant identifier, contract name, doc line)."""
    out = []
    out.append("/// {}\n".format(doc))
    out.append("#[non_exhaustive]\n")
    out.append("#[derive(Copy, Clone, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]\n")
    out.append("#[rustfmt::skip]\n")
    out.append("pub enum {} {{\n".format(name))
    for ident, _contract, line in entries:
        out.append("    /// {}\n".format(line))
        out.append("    {},\n".format(ident))
    out.append("}\n\n")
    out.append("#[rustfmt::skip]\n")
    out.append("impl {} {{\n".format(name))
    out.append("    /// Every variant, in declaration (sorted contract-name) order.\n")
    out.append("    pub const ALL: [{}; {}] = [\n".format(name, len(entries)))
    for ident, _contract, _line in entries:
        out.append("        {}::{},\n".format(name, ident))
    out.append("    ];\n\n")
    out.append("    /// The contract name used by the Python API, the CLI and the data files.\n")
    out.append("    pub const fn as_str(self) -> &'static str {\n")
    out.append("        match self {\n")
    for ident, contract, _line in entries:
        out.append("            {}::{} => {},\n".format(name, ident, json.dumps(contract)))
    out.append("        }\n")
    out.append("    }\n")
    out.append(extra_methods)
    out.append("}\n\n")
    out.append("#[rustfmt::skip]\n")
    out.append("impl FromStr for {} {{\n".format(name))
    out.append("    type Err = Error;\n\n")
    out.append("    fn from_str(name: &str) -> Result<{}, Error> {{\n".format(name))
    out.append("        match name {\n")
    for ident, contract, _line in entries:
        out.append("            {} => Ok({}::{}),\n".format(json.dumps(contract), name, ident))
    out.append("            _ => Err(Error::UnknownName {{ kind: {}, name: name.to_owned() }}),\n".format(json.dumps(kind)))
    out.append("        }\n")
    out.append("    }\n")
    out.append("}\n\n")
    out.append("#[rustfmt::skip]\n")
    out.append("impl fmt::Display for {} {{\n".format(name))
    out.append("    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {\n")
    out.append("        formatter.write_str(self.as_str())\n")
    out.append("    }\n")
    out.append("}\n")
    return "".join(out)


STRUCTURAL_DOCS = {
    "Mvs": "Structural token: Mongolian vowel separator U+180E (NNBSP U+202F is folded into it).",
    "Nirugu": "Structural token: nirugu U+180A, the visible stem extender.",
    "Zwj": "Structural token: zero width joiner U+200D.",
}


def render_enums(rules):
    units = set(STRUCTURAL_UNITS)
    conditions = set()
    aliases = set()
    for doc in rules.values():
        for letter in doc["letters"]:
            aliases.add(letter["alias"])
            for variant in letter["variants"]:
                units.update(variant["written"])
                conditions.update(variant["conditions"])
    unit_entries = [
        (unit_variant(unit), unit,
         STRUCTURAL_DOCS.get(unit, "Written unit `{}`.".format(unit)))
        for unit in sorted(units)
    ]
    condition_entries = [
        (condition_variant(name), name, "Shaping condition `{}`.".format(name))
        for name in sorted(conditions)
    ]
    alias_entries = [
        (alias_variant(alias), alias, "Letter alias `{}`.".format(alias))
        for alias in sorted(aliases)
    ]
    for entries, label in ((unit_entries, "unit"), (condition_entries, "condition"), (alias_entries, "alias")):
        idents = [entry[0] for entry in entries]
        if len(set(idents)) != len(idents):
            die("{} variant identifiers collide".format(label))

    is_structural = (
        "\n    /// `true` for the structural tokens `Mvs`, `Nirugu` and `Zwj`.\n"
        "    pub const fn is_structural(self) -> bool {\n"
        "        matches!(self, WrittenUnit::Mvs | WrittenUnit::Nirugu | WrittenUnit::Zwj)\n"
        "    }\n"
    )
    out = [HEADER, provenance([DATA / (locale + ".json") for locale in LOCALES]), "\n"]
    out.append("use std::fmt;\nuse std::str::FromStr;\n\nuse crate::Error;\n\n")
    out.append(render_enum(
        "WrittenUnit",
        "A written unit: an opaque glyph-form identifier produced by shaping (see `docs/data-format.md`). "
        "The structural tokens `Mvs`, `Nirugu` and `Zwj` are members too: they appear verbatim in "
        "[`Shaper::shape`](crate::Shaper::shape) output, exactly as the Python implementation emits them.",
        unit_entries, "written unit", is_structural))
    out.append("\n")
    out.append(render_enum(
        "Condition",
        "A shaping condition assigned by the rule pipeline; `as_str()` is the data-file name (`chachlag_onset`, ...).",
        condition_entries, "condition"))
    out.append("\n")
    out.append(render_enum(
        "Alias",
        "A letter alias (phonemic short name, locale-relative); `as_str()` is the data-file name (`a`, `oe`, `k2`, ...).",
        alias_entries, "alias"))
    return "".join(out)


def render_uses(body, candidates):
    """Emit one `use` per line, ASCII-sorted (rustfmt-stable), only for names the body uses."""
    lines = []
    for path in sorted(candidates):
        name = path.rsplit("::", 1)[1]
        if re.search(r"\b{}\b".format(re.escape(name)), body):
            lines.append("use {};\n".format(path))
    return "".join(lines)


LOCALE_USES = (
    "crate::generated::enums::Alias",
    "crate::generated::enums::Condition",
    "crate::generated::enums::WrittenUnit",
    "crate::tables::Categories",
    "crate::tables::Fvs",
    "crate::tables::Letter",
    "crate::tables::LocaleData",
    "crate::tables::Particle",
    "crate::tables::ParticleSym",
    "crate::tables::Position",
    "crate::tables::Variant",
)


def render_locale(locale, doc):
    body = []
    body.append("#[rustfmt::skip]\n")
    body.append("pub(crate) static DATA: LocaleData = LocaleData {\n")
    body.append("    letters: &[\n")
    for letter in doc["letters"]:
        body.append("        Letter {{ cp: {}, alias: Alias::{}, variants: &[\n".format(
            hex_cp(letter["cp"]), alias_variant(letter["alias"])))
        for variant in letter["variants"]:
            written = ", ".join("WrittenUnit::" + unit_variant(unit) for unit in variant["written"])
            conditions = ", ".join("Condition::" + condition_variant(name) for name in variant["conditions"])
            body.append(
                "            Variant {{ position: {}, fvs: {}, written: &[{}], default: {}, conditions: &[{}] }},\n".format(
                    position_variant(variant["position"]), fvs_expr(variant["fvs"]), written,
                    "true" if variant["default"] else "false", conditions))
        body.append("        ] },\n")
    body.append("    ],\n")
    body.append("    categories: Categories {\n")
    for field, key in (("vowel", "vowel"), ("consonant", "consonant"),
                       ("vowel_masculine", "vowelMasculine"), ("vowel_feminine", "vowelFeminine"),
                       ("vowel_neuter", "vowelNeuter")):
        members = ", ".join("Alias::" + alias_variant(alias) for alias in doc["categories"].get(key, []))
        body.append("        {}: &[{}],\n".format(field, members))
    body.append("    },\n")
    body.append("    particles: &[\n")
    for key, indices in doc["particles"].items():
        syms = ", ".join(
            "ParticleSym::Mvs" if part == "mvs" else "ParticleSym::Alias(Alias::{})".format(alias_variant(part))
            for part in key.split(" "))
        body.append("        Particle {{ key: &[{}], indices: &[{}] }},\n".format(
            syms, ", ".join(str(index) for index in indices)))
    body.append("    ],\n")
    body.append("};\n")
    body = "".join(body)
    source = DATA / (locale + ".json")
    header = HEADER + provenance([source]) + "// generated_from: {} {}\n".format(
        doc["generated_from"]["package"], doc["generated_from"]["version"])
    return header + "\n" + render_uses(body, LOCALE_USES) + "\n" + body


NORMALIZE_USES = (
    "crate::generated::enums::WrittenUnit",
    "crate::tables::Candidate",
    "crate::tables::ContextTable",
    "crate::tables::FinalEntry",
    "crate::tables::FinalValidity",
    "crate::tables::Fvs",
    "crate::tables::NormalizeData",
    "crate::tables::Position",
    "crate::tables::Robustness",
)


def units_expr(names):
    return "&[{}]".format(", ".join("WrittenUnit::" + unit_variant(unit) for unit in names.split("+")))


def table_expr(table, value_expr):
    rows = ", ".join("(0x{:x}, {})".format(int(key, 16), value_expr(value)) for key, value in table["rows"])
    return "ContextTable {{ projection: 0b{:010b}, default: {}, rows: &[{}] }}".format(
        projection_bits(table["projection"], "table"), value_expr(table["default"]), rows)


def render_normalize(locale, doc, aliases):
    written = doc["written_sequences"]
    body = []
    body.append("#[rustfmt::skip]\n")
    body.append("pub(crate) static DATA: NormalizeData = NormalizeData {\n")
    body.append("    canonical_version: {},\n".format(json.dumps(doc["canonical_version"])))
    body.append("    mask_sets: &[\n")
    for set_ in doc["mask_sets"]:
        body.append("        [{}],\n".format(", ".join("0x{:x}".format(int(mask, 16)) for mask in set_)))
    body.append("    ],\n")
    body.append("    candidates: &[\n")
    for cand in doc["candidates"]:
        fvs = "None" if cand["fvs"] is None else "Some(Fvs::Fvs{})".format(FVS_CP_TO_INDEX[cand["fvs"]])
        robust = cand["robust"]
        if robust == "always":
            robust_expr = "Robustness::Always"
        elif robust == "never":
            robust_expr = "Robustness::Never"
        else:
            robust_expr = "Robustness::Table({})".format(table_expr(robust, str))
        body.append(
            "        Candidate {{ cp: {}, fvs: {}, position: {}, units: {}, written_id: {}, robust: {} }},\n".format(
                hex_cp(int(cand["cp"], 16)), fvs, position_variant(cand["position"]), units_expr(cand["units"]),
                written.index(cand["written"]) + 1, robust_expr))
    body.append("    ],\n")
    body.append("    finals: &[\n")

    def mask(value):
        return "0b{:b}".format(int(value, 16))
    for entry in doc["finals"]:
        if isinstance(entry["valid"], dict):
            valid = "FinalValidity::Table({})".format(table_expr(entry["valid"], mask))
        else:
            valid = "FinalValidity::Always({})".format(mask(entry["valid"]))
        body.append("        FinalEntry {{ position: {}, units: {}, valid: {} }},\n".format(
            position_variant(entry["position"]), units_expr(entry["units"]), valid))
    body.append("    ],\n")
    body.append("    promises: [\n")
    for _name, letters in doc["promises"]:
        body.append("        &[{}],\n".format(", ".join(hex_cp(aliases[alias]) for alias in letters)))
    body.append("    ],\n")
    nodes = doc["particle_nodes"]
    body.append("    particle_nodes: &[\n")
    for name in nodes:
        if name in ("", "M:"):
            body.append("        (u16::MAX, 0),\n")
        else:
            parent, alias = particle_parent(name)
            body.append("        ({}, {}),\n".format(nodes.index(parent), hex_cp(aliases[alias])))
    body.append("    ],\n")
    body.append("    known_units: &[{}],\n".format(
        ", ".join("WrittenUnit::" + unit_variant(unit) for unit in doc["known_units"])))
    body.append("    positioned_units: &[\n")
    for record in doc["positioned_units"]:
        body.append("        (WrittenUnit::{}, {}),\n".format(
            unit_variant(record["unit"]), position_variant(record["position"])))
    body.append("    ],\n")
    body.append("};\n")
    body = "".join(body)
    source = DATA / (locale + ".normalize.json")
    header = HEADER + provenance([source]) + "// canonical_version: {}\n".format(doc["canonical_version"])
    return header + "\n" + render_uses(body, NORMALIZE_USES) + "\n" + body


def render_mod(files):
    out = [HEADER, "\n"]
    for name in sorted(files):
        out.append("pub mod {};\n".format(name))
    return "".join(out)


def render_all():
    rules, aliases = load_rules()
    normalize = load_normalize(rules, aliases)
    files = {"enums.rs": render_enums(rules)}
    for locale in LOCALES:
        files[locale.lower() + ".rs"] = render_locale(locale, rules[locale])
    for locale in NORMALIZE_LOCALES:
        files[locale.lower() + "_normalize.rs"] = render_normalize(locale, normalize[locale], aliases[locale])
    files["mod.rs"] = render_mod([name[:-3] for name in files])
    return files


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true",
                        help="verify that the committed generated files are up to date (exit 1 otherwise)")
    args = parser.parse_args()
    files = render_all()
    if args.check:
        stale = []
        for name, text in sorted(files.items()):
            path = OUT / name
            if not path.exists():
                stale.append("missing: " + path.relative_to(ROOT).as_posix())
            elif path.read_text(encoding="utf-8") != text:
                stale.append("stale:   " + path.relative_to(ROOT).as_posix())
        if OUT.exists():
            for path in sorted(OUT.glob("*.rs")):
                if path.name not in files:
                    stale.append("unexpected: " + path.relative_to(ROOT).as_posix())
        if stale:
            print("\n".join(stale))
            print("run: python3 python/scripts/gen_rust_tables.py")
            return 1
        print("generated Rust tables are fresh ({} files)".format(len(files)))
        return 0
    OUT.mkdir(parents=True, exist_ok=True)
    for name, text in sorted(files.items()):
        (OUT / name).write_text(text, encoding="utf-8")
        print("wrote", (OUT / name).relative_to(ROOT).as_posix())
    return 0


if __name__ == "__main__":
    sys.exit(main())
