#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Generate the static Rust data tables for the Rust core (crates/mongol-norm).

Reads the language-agnostic JSON in `mongol_norm/data/` -- the same files the
Python runtime loads -- and emits `crates/mongol-norm/src/generated/*.rs`:

  enums.rs            WrittenUnit / Condition / Alias enums (union over all locales)
  mng.rs tod.rs ...   per-locale shaping tables (letters, variants, categories, particles)
  mng_normalize.rs    the MNG normalize table
  mod.rs              module declarations

The output is deterministic (no timestamps, stable ordering), so `--check`
regenerates into memory and fails when any committed file differs.
tests/test_rust_twin.py runs that check in the Python test suite.

    python3 scripts/gen_rust_tables.py          # (re)generate
    python3 scripts/gen_rust_tables.py --check  # verify freshness; exit 1 if stale

Python 3.9+, standard library only.
"""
import argparse
import hashlib
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "mongol_norm" / "data"
OUT = ROOT / "crates" / "mongol-norm" / "src" / "generated"

LOCALES = ("MNG", "TOD", "SIB", "MCH")
NORMALIZE_LOCALES = ("MNG",)
STRUCTURAL_UNITS = ("Mvs", "Nirugu", "Zwj")
POSITIONS = ("isol", "init", "medi", "fina")
SCHEMA_VERSION = 1
NORMALIZE_SCHEMA = "mongol-normalize-table/1"
CANONICAL_VERSION = "mng-canonical/1"
MAX_UNIT_KEY_LEN = 3  # crates/mongol-norm/src/normalize.rs::UnitKey capacity
# Must equal the constants in crates/mongol-norm/src/unicode.rs.
CONSTANTS = {
    "MVS": "180E", "NIRUGU": "180A", "ZWJ": "200D",
    "FVS1": "180B", "FVS2": "180C", "FVS3": "180D", "FVS4": "180F",
}
FVS_CP_TO_INDEX = {"180B": 1, "180C": 2, "180D": 3, "180F": 4}

UNIT_NAME = re.compile(r"^[A-Z][A-Za-z0-9]*$")
CONDITION_NAME = re.compile(r"^[a-z][a-z0-9_]*$")
ALIAS_NAME = re.compile(r"^[a-z][a-z0-9]*$")

HEADER = "// @generated by scripts/gen_rust_tables.py -- DO NOT EDIT.\n"


def die(message):
    raise SystemExit("gen_rust_tables: " + message)


def digest(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()[:16]


def condition_variant(name):
    if not CONDITION_NAME.match(name):
        die("bad condition name {!r}".format(name))
    return "".join(part.capitalize() for part in name.split("_"))


def alias_variant(alias):
    if not ALIAS_NAME.match(alias):
        die("bad alias {!r}".format(alias))
    return alias[0].upper() + alias[1:]


def unit_variant(unit):
    if not UNIT_NAME.match(unit):
        die("bad written unit name {!r}".format(unit))
    return unit


def position_variant(position):
    if position not in POSITIONS:
        die("bad position {!r}".format(position))
    return "Position::" + position.capitalize()


def fvs_expr(index):
    if index == 0:
        return "None"
    if index not in (1, 2, 3, 4):
        die("bad fvs {!r}".format(index))
    return "Some(Fvs::Fvs{})".format(index)


def hex_cp(value):
    return "0x{:04X}".format(value)


# ── loading + validation ───────────────────────────────────────────────

def load_rules():
    rules = {}
    for locale in LOCALES:
        path = DATA / (locale + ".json")
        with path.open(encoding="utf-8") as stream:
            doc = json.load(stream)
        if doc.get("schema_version") != SCHEMA_VERSION:
            die("{}: schema_version {!r} != {}".format(path.name, doc.get("schema_version"), SCHEMA_VERSION))
        if doc.get("locale") != locale:
            die("{}: locale mismatch".format(path.name))
        validate_rules(locale, doc)
        rules[locale] = doc
    return rules


def validate_rules(locale, doc):
    seen_keys = set()
    defaults = set()
    slots = set()
    aliases = {}
    for letter in doc["letters"]:
        alias = letter.get("alias")
        if not alias:
            die("{}: letter U+{:04X} has no alias".format(locale, letter["cp"]))
        alias_variant(alias)
        if alias in aliases:
            die("{}: duplicate alias {!r}".format(locale, alias))
        aliases[alias] = letter["cp"]
        if not letter["variants"]:
            die("{}: letter {!r} has no variants".format(locale, alias))
        for variant in letter["variants"]:
            position_variant(variant["position"])
            fvs_expr(variant["fvs"])
            key = (letter["cp"], variant["position"], variant["fvs"])
            if key in seen_keys:
                die("{}: duplicate variant {!r}".format(locale, key))
            seen_keys.add(key)
            slots.add((letter["cp"], variant["position"]))
            written = variant["written"]
            if not written or len(written) > MAX_UNIT_KEY_LEN:
                die("{}: variant {!r} has {} written units".format(locale, key, len(written)))
            for unit in written:
                unit_variant(unit)
                if unit in STRUCTURAL_UNITS:
                    die("{}: written unit {!r} collides with a structural token".format(locale, unit))
            for condition in variant["conditions"]:
                condition_variant(condition)
            if variant["default"]:
                if (letter["cp"], variant["position"]) in defaults:
                    die("{}: two defaults for {!r}".format(locale, key[:2]))
                defaults.add((letter["cp"], variant["position"]))
    missing = slots - defaults
    if missing:
        die("{}: (cp, position) without a default variant: {!r}".format(locale, sorted(missing)))
    for category, members in doc["categories"].items():
        for alias in members:
            if alias not in aliases:
                die("{}: category {!r} names unknown alias {!r}".format(locale, category, alias))
    for key, indices in doc["particles"].items():
        parts = key.split(" ")
        for part in parts:
            if part != "mvs" and part not in aliases:
                die("{}: particle {!r} names unknown alias {!r}".format(locale, key, part))
        for index in indices:
            if not isinstance(index, int) or not 0 <= index < len(parts):
                die("{}: particle {!r} has bad index {!r}".format(locale, key, index))
    return aliases


def load_normalize(rules):
    tables = {}
    for locale in NORMALIZE_LOCALES:
        path = DATA / (locale + ".normalize.json")
        with path.open(encoding="utf-8") as stream:
            doc = json.load(stream)
        if doc.get("schema") != NORMALIZE_SCHEMA:
            die("{}: schema {!r}".format(path.name, doc.get("schema")))
        if doc.get("canonical_version") != CANONICAL_VERSION:
            die("{}: canonical_version {!r}".format(path.name, doc.get("canonical_version")))
        if doc.get("locale") != locale:
            die("{}: locale mismatch".format(path.name))
        for name, value in CONSTANTS.items():
            if doc["constants"].get(name) != value:
                die("{}: constant {} is {!r}, expected {!r}".format(path.name, name, doc["constants"].get(name), value))
        validate_normalize(locale, doc, rules[locale])
        tables[locale] = doc
    return tables


def locale_units(doc):
    return {unit for letter in doc["letters"] for variant in letter["variants"] for unit in variant["written"]}


def validate_normalize(locale, doc, rules_doc):
    units = locale_units(rules_doc)
    cps = {letter["cp"] for letter in rules_doc["letters"]}
    max_len = 0
    for section in ("unit_table", "velar_fem"):
        for position, entries in doc[section].items():
            position_variant(position)
            for key, entry in entries.items():
                parts = key.split("+")
                max_len = max(max_len, len(parts))
                for unit in parts:
                    if unit not in units:
                        die("{}: {} names unknown unit {!r}".format(locale, section, unit))
                if int(entry["cp"], 16) not in cps:
                    die("{}: {} entry {!r} has unknown cp {!r}".format(locale, section, key, entry["cp"]))
                if entry["fvs"] is not None and entry["fvs"] not in FVS_CP_TO_INDEX:
                    die("{}: {} entry {!r} has bad fvs {!r}".format(locale, section, key, entry["fvs"]))
    if max_len > MAX_UNIT_KEY_LEN:
        die("{}: unit key longer than {}".format(locale, MAX_UNIT_KEY_LEN))
    if doc["unit_enc_max_len"] != max_len:
        die("{}: unit_enc_max_len {} != longest key {}".format(locale, doc["unit_enc_max_len"], max_len))
    for unit in doc["velar_fem_units"]:
        if unit not in units:
            die("{}: velar_fem_units names unknown unit {!r}".format(locale, unit))
    aliases = {letter["alias"]: letter["cp"] for letter in rules_doc["letters"]}
    for masc, fem in doc["masc_to_fem"].items():
        if masc not in aliases or fem not in aliases:
            die("{}: masc_to_fem names unknown alias".format(locale))
    for record in doc["positioned_units"]:
        if record["unit"] not in units:
            die("{}: positioned_units names unknown unit {!r}".format(locale, record["unit"]))
        position_variant(record["position"])


# ── rendering ──────────────────────────────────────────────────────────

def provenance(paths):
    lines = []
    for path in paths:
        lines.append("// Source: {} (sha256 {})\n".format(path.relative_to(ROOT).as_posix(), digest(path)))
    return "".join(lines)


def render_enum(name, doc, entries, kind, extra_methods=""):
    """entries: list of (variant identifier, contract name, doc line)."""
    out = []
    out.append("/// {}\n".format(doc))
    out.append("#[non_exhaustive]\n")
    out.append("#[derive(Copy, Clone, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]\n")
    out.append("#[rustfmt::skip]\n")
    out.append("pub enum {} {{\n".format(name))
    for ident, _contract, line in entries:
        out.append("    /// {}\n".format(line))
        out.append("    {},\n".format(ident))
    out.append("}\n\n")
    out.append("#[rustfmt::skip]\n")
    out.append("impl {} {{\n".format(name))
    out.append("    /// Every variant, in declaration (sorted contract-name) order.\n")
    out.append("    pub const ALL: &'static [{}] = &[\n".format(name))
    for ident, _contract, _line in entries:
        out.append("        {}::{},\n".format(name, ident))
    out.append("    ];\n\n")
    out.append("    /// The contract name used by the Python API, the CLI and the data files.\n")
    out.append("    pub const fn as_str(self) -> &'static str {\n")
    out.append("        match self {\n")
    for ident, contract, _line in entries:
        out.append("            {}::{} => {},\n".format(name, ident, json.dumps(contract)))
    out.append("        }\n")
    out.append("    }\n")
    out.append(extra_methods)
    out.append("}\n\n")
    out.append("#[rustfmt::skip]\n")
    out.append("impl FromStr for {} {{\n".format(name))
    out.append("    type Err = Error;\n\n")
    out.append("    fn from_str(name: &str) -> Result<{}, Error> {{\n".format(name))
    out.append("        match name {\n")
    for ident, contract, _line in entries:
        out.append("            {} => Ok({}::{}),\n".format(json.dumps(contract), name, ident))
    out.append("            _ => Err(Error::UnknownName {{ kind: {}, name: name.to_owned() }}),\n".format(json.dumps(kind)))
    out.append("        }\n")
    out.append("    }\n")
    out.append("}\n\n")
    out.append("#[rustfmt::skip]\n")
    out.append("impl fmt::Display for {} {{\n".format(name))
    out.append("    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {\n")
    out.append("        formatter.write_str(self.as_str())\n")
    out.append("    }\n")
    out.append("}\n")
    return "".join(out)


STRUCTURAL_DOCS = {
    "Mvs": "Structural token: Mongolian vowel separator U+180E (NNBSP U+202F is folded into it).",
    "Nirugu": "Structural token: nirugu U+180A, the visible stem extender.",
    "Zwj": "Structural token: zero width joiner U+200D.",
}


def render_enums(rules):
    units = set(STRUCTURAL_UNITS)
    conditions = set()
    aliases = set()
    for doc in rules.values():
        for letter in doc["letters"]:
            aliases.add(letter["alias"])
            for variant in letter["variants"]:
                units.update(variant["written"])
                conditions.update(variant["conditions"])
    unit_entries = [
        (unit_variant(unit), unit,
         STRUCTURAL_DOCS.get(unit, "Written unit `{}`.".format(unit)))
        for unit in sorted(units)
    ]
    condition_entries = [
        (condition_variant(name), name, "Shaping condition `{}`.".format(name))
        for name in sorted(conditions)
    ]
    alias_entries = [
        (alias_variant(alias), alias, "Letter alias `{}`.".format(alias))
        for alias in sorted(aliases)
    ]
    for entries, label in ((unit_entries, "unit"), (condition_entries, "condition"), (alias_entries, "alias")):
        idents = [entry[0] for entry in entries]
        if len(set(idents)) != len(idents):
            die("{} variant identifiers collide".format(label))

    is_structural = (
        "\n    /// `true` for the structural tokens `Mvs`, `Nirugu` and `Zwj`.\n"
        "    pub const fn is_structural(self) -> bool {\n"
        "        matches!(self, WrittenUnit::Mvs | WrittenUnit::Nirugu | WrittenUnit::Zwj)\n"
        "    }\n"
    )
    out = [HEADER, provenance([DATA / (locale + ".json") for locale in LOCALES]), "\n"]
    out.append("use std::fmt;\nuse std::str::FromStr;\n\nuse crate::Error;\n\n")
    out.append(render_enum(
        "WrittenUnit",
        "A written unit: an opaque glyph-form identifier produced by shaping (see `docs/data-format.md`). "
        "The structural tokens `Mvs`, `Nirugu` and `Zwj` are members too: they appear verbatim in "
        "[`Shaper::shape`](crate::Shaper::shape) output, exactly as the Python implementation emits them.",
        unit_entries, "written unit", is_structural))
    out.append("\n")
    out.append(render_enum(
        "Condition",
        "A shaping condition assigned by the rule pipeline; `as_str()` is the data-file name (`chachlag_onset`, ...).",
        condition_entries, "condition"))
    out.append("\n")
    out.append(render_enum(
        "Alias",
        "A letter alias (phonemic short name, locale-relative); `as_str()` is the data-file name (`a`, `oe`, `k2`, ...).",
        alias_entries, "alias"))
    return "".join(out)


def render_uses(body, candidates):
    """Emit one `use` per line, ASCII-sorted (rustfmt-stable), only for names the body uses."""
    lines = []
    for path in sorted(candidates):
        name = path.rsplit("::", 1)[1]
        if re.search(r"\b{}\b".format(re.escape(name)), body):
            lines.append("use {};\n".format(path))
    return "".join(lines)


LOCALE_USES = (
    "crate::generated::enums::Alias",
    "crate::generated::enums::Condition",
    "crate::generated::enums::WrittenUnit",
    "crate::tables::Categories",
    "crate::tables::Fvs",
    "crate::tables::Letter",
    "crate::tables::LocaleData",
    "crate::tables::Particle",
    "crate::tables::ParticleSym",
    "crate::tables::Position",
    "crate::tables::Variant",
)


def render_locale(locale, doc):
    body = []
    body.append("#[rustfmt::skip]\n")
    body.append("pub(crate) static DATA: LocaleData = LocaleData {\n")
    body.append("    letters: &[\n")
    for letter in doc["letters"]:
        body.append("        Letter {{ cp: {}, alias: Alias::{}, variants: &[\n".format(
            hex_cp(letter["cp"]), alias_variant(letter["alias"])))
        for variant in letter["variants"]:
            written = ", ".join("WrittenUnit::" + unit_variant(unit) for unit in variant["written"])
            conditions = ", ".join("Condition::" + condition_variant(name) for name in variant["conditions"])
            body.append(
                "            Variant {{ position: {}, fvs: {}, written: &[{}], default: {}, conditions: &[{}] }},\n".format(
                    position_variant(variant["position"]), fvs_expr(variant["fvs"]), written,
                    "true" if variant["default"] else "false", conditions))
        body.append("        ] },\n")
    body.append("    ],\n")
    body.append("    categories: Categories {\n")
    for field, key in (("vowel", "vowel"), ("consonant", "consonant"),
                       ("vowel_masculine", "vowelMasculine"), ("vowel_feminine", "vowelFeminine"),
                       ("vowel_neuter", "vowelNeuter")):
        members = ", ".join("Alias::" + alias_variant(alias) for alias in doc["categories"].get(key, []))
        body.append("        {}: &[{}],\n".format(field, members))
    body.append("    },\n")
    body.append("    particles: &[\n")
    for key, indices in doc["particles"].items():
        syms = ", ".join(
            "ParticleSym::Mvs" if part == "mvs" else "ParticleSym::Alias(Alias::{})".format(alias_variant(part))
            for part in key.split(" "))
        body.append("        Particle {{ key: &[{}], indices: &[{}] }},\n".format(
            syms, ", ".join(str(index) for index in indices)))
    body.append("    ],\n")
    body.append("};\n")
    body = "".join(body)
    source = DATA / (locale + ".json")
    header = HEADER + provenance([source]) + "// generated_from: {} {}\n".format(
        doc["generated_from"]["package"], doc["generated_from"]["version"])
    return header + "\n" + render_uses(body, LOCALE_USES) + "\n" + body


NORMALIZE_USES = (
    "crate::generated::enums::WrittenUnit",
    "crate::tables::Fvs",
    "crate::tables::NormalizeData",
    "crate::tables::Position",
    "crate::tables::UnitEntry",
)


def render_entries(section):
    lines = []
    for position in POSITIONS:
        for key, entry in section.get(position, {}).items():
            units = ", ".join("WrittenUnit::" + unit_variant(unit) for unit in key.split("+"))
            fvs = "None" if entry["fvs"] is None else "Some(Fvs::Fvs{})".format(FVS_CP_TO_INDEX[entry["fvs"]])
            lines.append("        UnitEntry {{ position: {}, units: &[{}], cp: {}, fvs: {} }},\n".format(
                position_variant(position), units, hex_cp(int(entry["cp"], 16)), fvs))
    return "".join(lines)


def render_normalize(locale, doc, rules_doc):
    aliases = {letter["alias"]: letter["cp"] for letter in rules_doc["letters"]}
    body = []
    body.append("#[rustfmt::skip]\n")
    body.append("pub(crate) static DATA: NormalizeData = NormalizeData {\n")
    body.append("    canonical_version: {},\n".format(json.dumps(doc["canonical_version"])))
    body.append("    unit_enc_max_len: {},\n".format(doc["unit_enc_max_len"]))
    body.append("    unit_table: &[\n")
    body.append(render_entries(doc["unit_table"]))
    body.append("    ],\n")
    body.append("    velar_fem: &[\n")
    body.append(render_entries(doc["velar_fem"]))
    body.append("    ],\n")
    body.append("    velar_fem_units: &[{}],\n".format(
        ", ".join("WrittenUnit::" + unit_variant(unit) for unit in doc["velar_fem_units"])))
    pairs = sorted((aliases[masc], aliases[fem]) for masc, fem in doc["masc_to_fem"].items())
    body.append("    masc_to_fem: &[{}],\n".format(
        ", ".join("({}, {})".format(hex_cp(masc), hex_cp(fem)) for masc, fem in pairs)))
    body.append("    positioned_units: &[\n")
    for record in doc["positioned_units"]:
        body.append("        (WrittenUnit::{}, {}),\n".format(
            unit_variant(record["unit"]), position_variant(record["position"])))
    body.append("    ],\n")
    body.append("};\n")
    body = "".join(body)
    source = DATA / (locale + ".normalize.json")
    header = HEADER + provenance([source]) + "// canonical_version: {}\n".format(doc["canonical_version"])
    return header + "\n" + render_uses(body, NORMALIZE_USES) + "\n" + body


def render_mod(files):
    out = [HEADER, "\n"]
    for name in sorted(files):
        out.append("pub mod {};\n".format(name))
    return "".join(out)


def render_all():
    rules = load_rules()
    normalize = load_normalize(rules)
    files = {"enums.rs": render_enums(rules)}
    for locale in LOCALES:
        files[locale.lower() + ".rs"] = render_locale(locale, rules[locale])
    for locale in NORMALIZE_LOCALES:
        files[locale.lower() + "_normalize.rs"] = render_normalize(locale, normalize[locale], rules[locale])
    files["mod.rs"] = render_mod([name[:-3] for name in files])
    return files


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true",
                        help="verify that the committed generated files are up to date (exit 1 otherwise)")
    args = parser.parse_args()
    files = render_all()
    if args.check:
        stale = []
        for name, text in sorted(files.items()):
            path = OUT / name
            if not path.exists():
                stale.append("missing: " + path.relative_to(ROOT).as_posix())
            elif path.read_text(encoding="utf-8") != text:
                stale.append("stale:   " + path.relative_to(ROOT).as_posix())
        if OUT.exists():
            for path in sorted(OUT.glob("*.rs")):
                if path.name not in files:
                    stale.append("unexpected: " + path.relative_to(ROOT).as_posix())
        if stale:
            print("\n".join(stale))
            print("run: python3 scripts/gen_rust_tables.py")
            return 1
        print("generated Rust tables are fresh ({} files)".format(len(files)))
        return 0
    OUT.mkdir(parents=True, exist_ok=True)
    for name, text in sorted(files.items()):
        (OUT / name).write_text(text, encoding="utf-8")
        print("wrote", (OUT / name).relative_to(ROOT).as_posix())
    return 0


if __name__ == "__main__":
    sys.exit(main())
