"""
Tests for the bundled normalize table (`python/mongol_norm/data/MNG.normalize.json`,
schema `mongol-normalize-table/2`): the tables of the online normalize encoder,
which `python/scripts/gen_rust_tables.py` compiles into the engine (and
validates structurally; `python/tests/test_rust_twin.py` checks that step is
fresh, and the canonical golden proves what the compiled tables encode).

The table is generated by the Rust example `examples/gen_normalize_table`
(`python/scripts/gen_normalize_table.py` runs it); its `--check` is the
freshness gate, run by CI's Rust job. These tests check what the file promises
against the compiled engine.
随包归一化表(在线编码器的表)的测试:由 Rust example 生成(其 --check 由 CI
的 Rust 任务把关);这里对照编译后的引擎检查表的承诺。
"""
import unittest

from mongol_norm import MongolianShaper
from mongol_norm._data import load_normalize_table

_FVS = frozenset("᠋᠌᠍᠏")


def _text(option):
    """The Unicode text of an encoding option: the letter and its FVS, if any."""
    fvs = chr(int(option["fvs"], 16)) if option["fvs"] else ""
    return chr(int(option["cp"], 16)) + fvs


def _rank(option):
    """The documented tie-break among equally short options: code point order,
    except `g` before `h` (ᠭᠡᠷ, not ᠬᠡᠷ); then the FVS."""
    cp = int(option["cp"], 16)
    rank = 0x182C * 2 - 1 if cp == 0x182D else cp * 2
    cost = 2 if option["fvs"] else 1
    return cost, rank, option["fvs"] or ""


class TestNormalizeTable(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.s = MongolianShaper(locale="MNG")
        cls.table = load_normalize_table("MNG")

    def test_schema_and_canonical_version(self):
        table = self.table
        self.assertEqual(table["schema"], "mongol-normalize-table/2")
        self.assertEqual(table["locale"], "MNG")
        self.assertEqual(table["canonical_version"], "mng-canonical/3")
        self.assertEqual(self.s.canonical_version, table["canonical_version"])
        for key in ("context_components", "promises", "particle_nodes",
                    "written_sequences", "mask_units", "mask_sets",
                    "candidates", "finals", "known_units", "positioned_units"):
            self.assertIn(key, table, f"table missing {key!r}")

    def test_options_are_grouped_in_preference_order(self):
        """Options of one (position, written units) group are contiguous and
        in preference order: shortest first, then the documented rank."""
        groups = {}
        previous = None
        for option in self.table["candidates"]:
            slot = (option["position"], option["units"])
            if slot != previous:
                self.assertNotIn(slot, groups, f"group {slot} is not contiguous")
                groups[slot] = []
                previous = slot
            groups[slot].append(option)
        for slot, options in groups.items():
            with self.subTest(slot=slot):
                self.assertEqual(options, sorted(options, key=_rank))

    def test_context_free_options_render_their_units(self):
        """An option the table commits in every context ("always") renders
        its written units at its position whatever its neighbours — checked
        here with a plain (n) and a bowed (b) neighbour, and after an MVS."""
        neighbours = ("ᠨ", "ᠪ")  # n, b
        checked = 0
        for option in self.table["candidates"]:
            if option["robust"] != "always":
                continue
            position = option["position"]
            lefts = neighbours if position in ("medi", "fina") else ("", "᠎")
            rights = neighbours if position in ("init", "medi") else ("", "᠎")
            for left in lefts:
                for right in rights:
                    text = left + _text(option) + right
                    detail = self.s.shape_detailed(text)[len(left)]
                    with self.subTest(text=text):
                        self.assertEqual(detail["position"], position)
                        self.assertEqual("+".join(detail["written"]), option["written"])
                    checked += 1
        self.assertGreater(checked, 1000)

    def test_positioned_inventory_matches_hud_contract(self):
        pairs = {
            (record["unit"], record["position"])
            for record in self.table["positioned_units"]
        }
        self.assertEqual(len(pairs), 95)
        self.assertIn(("F", "init"), pairs)
        self.assertIn(("I", "isol"), pairs)
        self.assertNotIn(("F", "isol"), pairs)
        self.assertNotIn(("Zwj", "control"), pairs)


if __name__ == "__main__":
    unittest.main()
